import { useState } from 'react';
import { Routes, Route, useLocation } from 'react-router-dom';
import { AnimatePresence } from 'framer-motion';
import placeIdLookup from './placeIdLookup';
import Header from './components/layout/Header';
import Home from './pages/Home';
import Footer from './components/layout/Footer';
import FirestoreEx from './pages/FirestoreEx';
import MapView from './pages/MapView';
import PlacesEx from './pages/PlacesEx';
import StylingEx from './pages/StylingEx';
import TermsOfService from './pages/TermsOfService';
import PrivacyPolicy from './pages/PrivacyPolicy';
import PlaceDisplay from './pages/PlaceDisplay';

// Load the example dataset from local file.
const seedRatingsData = require('./ratingsData.json');

const App = () => {
  // A condition of use for infomation returned from the Google Places API is
  // that it is not stored or cached. Therefore the information returned from
  // the API will only be placed in the 'placesApiData' state temporarily and
  // cross-referenced with the data in 'ratingsData' state by checking the
  // 'place_id' field, of which storage is permitted.
  const [placesApiData, setPlacesApiData] = useState([]);
  // 'ratingsData' only retains information generated by this application.
  const [ratingsData, setRatingsData] = useState(seedRatingsData);
  const [currentPlace, setCurrentPlace] = useState({});
  const [userScores, setUserScores] = useState({});

  // useLocation allows the application to keep track of its current location.
  // in this case it provides the necessary information for framer-motion to
  // animate on a per route (page-by-page) basis.
  // Note: for useLocation to function correctly the Router must be defined in
  // a higher level component (in this case index.js).
  const location = useLocation();

  const handleCurrentPlace = (addressObject) => {
    setCurrentPlace(addressObject);
    // NOTE: When querying the Google Places APIs the autocomplete API populates
    // place information where the geocoding API only returns address information.
    // If it is possible to associate the addressObject data with an existing
    // rating, it will be done below to minimise queries needed in the map section
    // of the application.
    // TODO - add code to populate 'placesApiData' where applicable.
  };

  const handleRatingSubmit = (event) => {
    event.preventDefault();
    console.log('Rating Submit Button Press');
  };

  const addUserRating = () => {};

  return (
    <>
      <Header
        currentPlace={currentPlace}
        handleCurrentPlace={handleCurrentPlace}
      />
      <main className="container">
        {/* The exitBeforeEnter prop prevents loading a new page before the last
        page has fully exited. */}
        <AnimatePresence exitBeforeEnter>
          {/* Location object and key added to the Routes component by means
          of the useLocation() hook. */}
          <Routes location={location} key={location.key}>
            <Route path="/" exact element={<Home />} />
            <Route
              path="/map"
              exact
              element={<MapView ratingsData={ratingsData} />}
            />
            <Route
              path="/places"
              exact
              element={<PlacesEx onChange={() => null} />}
            />
            <Route
              path="/spot/:placeid"
              exact
              element={
                <PlaceDisplay
                  currentPlace={currentPlace}
                  ratingsData={ratingsData}
                  userScores={userScores}
                  placesApiData={placesApiData}
                  handleRatingSubmit={handleRatingSubmit}
                />
              }
            />
            <Route path="/terms" exact element={<TermsOfService />} />
            <Route path="/privacy" exact element={<PrivacyPolicy />} />
            <Route path="/firestore" exact element={<FirestoreEx />} />
            <Route path="/styling" exact element={<StylingEx />} />
          </Routes>
        </AnimatePresence>
      </main>
      <Footer />
    </>
  );
};

export default App;
