import { useState } from 'react';
import { Routes, Route, useLocation } from 'react-router-dom';
import { AnimatePresence } from 'framer-motion';
import { useLocalStorage } from './hooks/useLocalStorage';
import placeIdLookup from './placeIdLookup';
import Header from './components/layout/Header';
import Home from './pages/Home';
import Footer from './components/layout/Footer';
import FirestoreEx from './pages/FirestoreEx';
import MapView from './pages/MapView';
import TermsOfService from './pages/TermsOfService';
import PrivacyPolicy from './pages/PrivacyPolicy';
import PlaceDisplay from './pages/PlaceDisplay';

// Load the example dataset from local file.
const seedRatingsData = require('./ratingsData.json');

// Define what the empty user scores form should look like. This is also used
// on form reset.
const emptyUserScores = [
  { category: 'Noise', score: 50, comment: '' },
  { category: 'Social', score: 50, comment: '' },
  { category: 'Coworking', score: 50, comment: '' },
  { category: 'Internet', score: 50, comment: '' },
  { category: 'Power', score: 50, comment: '' },
  { category: 'Accessibility', score: 50, comment: '' }
];

const App = () => {
  // A condition of use for infomation returned from the Google Places API is
  // that it is not stored or cached. Therefore the information returned from
  // the API will only be placed in the 'placesApiData' state temporarily and
  // cross-referenced with the data in 'ratingsData' state by checking the
  // 'place_id' field, of which storage is permitted.
  const [placesApiData, setPlacesApiData] = useState([]);
  // 'ratingsData' only retains information generated by this application, and
  // not the Google Places API:
  const [ratingsData, setRatingsData] = useState(seedRatingsData);
  const [currentPlace, setCurrentPlace] = useState({});
  // Provide an object containing form data for user ratings:
  const [userScores, setUserScores] = useState(emptyUserScores);

  // useLocation allows the application to keep track of its current location.
  // in this case it provides the necessary information for framer-motion to
  // animate on a per route (page-by-page) basis.
  // Note: for useLocation to function correctly the Router must be defined in
  // a higher level component (in this case index.js).
  const location = useLocation();

  const handleCurrentPlace = (addressObject) => {
    setCurrentPlace(addressObject);
    // NOTE: When querying the Google Places APIs the autocomplete API populates
    // place information where the geocoding API only returns address information.
    // If it is possible to associate the addressObject data with an existing
    // rating, it will be done below to minimise queries needed in the map section
    // of the application.
    // TODO - add code to populate 'placesApiData' where applicable.
  };

  // Determine which category in the userScores array needs to be updated and
  // replace with the new form data at that location.
  const handleScoreChange = (category, value) => {
    let newUserScores = userScores.map((score) => {
      if (score.category === category) {
        return {
          ...score,
          ...value
        };
      }
      return score;
    });
    setUserScores(newUserScores);
  };

  const handleFormReset = (event) => {
    event.preventDefault();
    console.log('FORM RESET!');
  };

  // Determine which element in the ratingsData array needs to be appended to
  // and add the new ratings in their appropriate locations. New overall rating
  // values must also be calculated at this stage.
  const handleScoresSubmit = (event) => {
    event.preventDefault();
    console.log('Rating Submit Button Press');
  };

  return (
    <>
      <Header
        currentPlace={currentPlace}
        handleCurrentPlace={handleCurrentPlace}
      />
      <main className="container">
        {/* The exitBeforeEnter prop prevents loading a new page before the last
        page has fully exited. */}
        <AnimatePresence exitBeforeEnter>
          {/* Location object and key added to the Routes component by means
          of the useLocation() hook. */}
          <Routes location={location} key={location.key}>
            <Route path="/" exact element={<Home />} />
            <Route
              path="/map"
              exact
              element={<MapView ratingsData={ratingsData} />}
            />
            <Route
              path="/spot/:placeid"
              exact
              element={
                <PlaceDisplay
                  currentPlace={currentPlace}
                  ratingsData={ratingsData}
                  userScores={userScores}
                  handleScoreChange={handleScoreChange}
                  handleFormReset={handleFormReset}
                  handleScoresSubmit={handleScoresSubmit}
                />
              }
            />
            <Route path="/terms" exact element={<TermsOfService />} />
            <Route path="/privacy" exact element={<PrivacyPolicy />} />
            <Route path="/firestore" exact element={<FirestoreEx />} />
          </Routes>
        </AnimatePresence>
      </main>
      <Footer />
    </>
  );
};

export default App;
